### PR TITLE
Use proper C++ headers

### PR DESCRIPTION
**Pull request by janisozaur**

### CODE REVIEW

**Comment by 983** [comment]
`#include <cstdint>` is not guaranteed to import all symbols into global scope, so it would be necessary to prefix all types with `std::`, which is ugly. Do you have a platform where the current code does not compile?

**Comment by janisozaur** [comment]
I don't think your argument is correct. Via https://eel.is/c++draft/requirements#headers-5 (emphasis mine):

> Except as noted in [library] through [thread] and [depr], the **contents of each header `cname` is the same as that of the corresponding header `name.h`** as specified in the C standard library.

Basically, in C++ all you get is a finite and well-defined set of headers, listed in the quoted section, and neither `string.h` nor `stdint.h` are in it. The symbols are _also_ available via `std` namespace, but it is not required to use it.

**Comment by janisozaur** [comment]
To further reinforce my point, please follow the links to major C++ library implementations:

https://github.com/llvm/llvm-project/blob/e26c24b849211f35a988d001753e0cd15e4a9d7b/libcxx/include/cstdint#L144
https://github.com/llvm/llvm-project/blob/687bbf85de4ae463c0794dff545734e194941162/libcxx/include/cstring#L60

https://github.com/gcc-mirror/gcc/blob/37462a131c528d0980915d98567361aa9396b030/libstdc%2B%2B-v3/include/tr1/cstdint#L46
https://github.com/gcc-mirror/gcc/blob/37462a131c528d0980915d98567361aa9396b030/libstdc%2B%2B-v3/include/c_std/cstring#L45

https://github.com/microsoft/STL/blob/ed3cbf36416a385828e7a5987ca52cb42882d84b/stl/inc/cstdint#L12
https://github.com/microsoft/STL/blob/ed3cbf36416a385828e7a5987ca52cb42882d84b/stl/inc/cstring#L12

**Comment by 983** [comment]
The next sentence of your [quoted source](https://eel.is/c++draft/requirements#headers-5) says:

> In the C++ standard library, however, the declarations (except for names which are defined as macros in C) are within namespace scope of the namespace std.

In addition, [the community consensus](https://stackoverflow.com/a/13643019) seems to be that using `cstdint` without `std::` is worse than using deprecated `stdint.h`.

**Comment by 983** [comment]
I became older and wiser (mostly older) and changed my mind. You were right. I still do not like it though.

**Pull request merged**
